name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Dark Snake SVG with Vibrant Colors
        uses: Platane/snk@v3
        with:
          github_user_name: wedoforall
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#ff6ec7,#00fff7,#ff9f1c,#9d4edd,#00ff87&color_dots=#ffe227,#ff3cac,#32ff7e,#0f0f0f,#5f0f40

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
